config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"
  resources :todos
  resources :users
  post "users/login", to: "users#findUser"

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  def to_pleasant_string
    is_completed = completed ? "[X]" : "[ ]"
    "#{id} #{due_date.to_s(:long)} #{todo_text} #{is_completed}"
  end

  def self.overdue
    all.where("due_date < ?", Date.today)
  end

  def self.due_today
    all.where("due_date = ?", Date.today)
  end

  def self.due_later
    all.where("due_date > ?", Date.today)
  end

  def self.completed
    all.where(completed: true)
  end

  def self.notCompleted
    all.where(completed: false)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :email, presence: true
  validates :password, length: { minimum: 3 }
  has_secure_password
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    #Memoization
    return @current_user if @current_user

    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Your login attempt was invalid. Please retry."
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
# todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos
    render "index"
  end

  def show
    id = params[:id]
    todo = Todo.of_user(current_user).find(id)
    render "todo"
  end

  def create
    todo_text = params[:todo_text]
    due_Date = params[:due_date]
    new_todo = Todo.new(
      todo_text: todo_text,
      due_date: due_Date,
      completed: false,
      user_id: current_user.id,
    )
    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = Todo.of_user(current_user).find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = Todo.of_user(current_user).find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "users/new"
  end

  def create
    user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
    )
    existing = User.find_by(email: user.email)
    if existing != nil
      flash[:error] = "Email already exists"
      render "users/new"
    else
      if user.save
        session[:current_user_id] = user.id
        redirect_to "/"
      else
        flash[:error] = user.errors.full_messages.join(", ")
        render "users/new"
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class="Home--title">Welcome to the Todo homepage</h1>

<h3 class="Home--authenticate">
  If you are a new user, <%= link_to "sign up here", new_user_path %>
</h3>

<h3 class="Home--authenticate">
  Existing users, <%= link_to "sign in here", new_sessions_path %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%=javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <p class="UserHeader">
        Welcome <%= @current_user.first_name %> !
        <%= link_to "Sign-out", destroy_session_path, method: "delete" %>
      </p>
    <% end %>

    <% if flash[:error] %>
      <p class="Flash-error">
        <%= flash[:error] %>
      </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
  <div class="TodoSection__title">
    <p class="TodoSection__title--text"><%= section_title %></p>
    <p class="TodoSection__title--remainingCount"><%= todos.completed.count %>/<%= todos.count %></p>
  </div>
  <ul>
    <% todos.each do |todo| %>
      <li class="TodoItem">
        <div class="TodoItem--container">
          <%= form_with(url: "/todos/#{todo.id}", method: "put") do %>

            <%= check_box_tag 'completed', nil, todo.completed,
            {:class => "TodoItem--checkbox", :onclick => "this.form.submit()"} %>

          <% end %>
          <p class='<%= todo.completed ? "TodoItem--completedText" : "" %>'>
            <%= todo.todo_text %>
          </p>
          <% if show_due_date %>
            <p class="TodoItem--dueDate"><%= todo.due_date.to_s(:short)%></p>
          <% end %>

          <a class="TodoItem--delete" href="javascript:void(0)">
            <%= form_with(url: "/todos/#{todo.id}", method: "delete") do %>
              <%= image_submit_tag("delete.png", alt: "submit") %>
            <% end %>
          </a>
        </div>
      </li>
    <% end %>
  </ul>
</section>

app/views/todos/index.html.erb
<article>
  <h1 class="TodoPage--title">My Todo-list</h1>
  <%= form_with(url: "/todos", method: "post", class: "AddTodo") do %>
    <%= text_field_tag 'todo_text', nil, class: "AddTodo--text", placeholder: "What's next?"  %>

    <%= date_field_tag 'due_date', nil, class: "AddTodo--date" %>

    <%= submit_tag "Add", class: "AddTodo--button" %>
  <% end %>

  <%= render partial: "todo-section", locals: {
    section_title: "Overdue",
    todos: Todo.overdue.notCompleted,
    show_due_date: true
    } %>
  <%= render partial: "todo-section", locals: {
    section_title: "Due Today",
    todos: Todo.due_today,
    show_due_date: false
    } %>
  <%= render partial: "todo-section", locals: {
    section_title: "Due Later",
    todos: Todo.due_later,
    show_due_date: true
    } %>

</article>

app/views/todos/todo.html.erb
<h1>Single Todo</h1>

app/views/users/new.html.erb
<p class="NewUsers--title">Welcome new user!</p>

<section>
  <%= form_with url: users_path do |form| %>
    <div class="Form-section">
      <p class="FormInput--label">First Name:</p>
      <%= form.text_field :first_name, class: "Form--input" %>
    </div>

    <div class="Form-section">
      <p class="FormInput--label">Last Name:</p>
      <%= form.text_field :last_name, class: "Form--input" %>
    </div>

    <div class="Form-section">
      <p class="FormInput--label">Email:</p>
      <%= form.email_field :email, class: "Form--input" %>
    </div>

    <div class="Form-section">
      <p class="FormInput--label">Password:</p>
      <%= form.password_field :password, class: "Form--input" %>
    </div>

    <div class="Form-section">
      <%= form.submit "Sign-Up!", class: "Form--submit" %>
    </div>
  <% end %>
</section>